name: 'ChatgptPluginTodo'
description: 'Starts a simple ChatGPT plugin.'
branding:
  icon: 'server'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '<your_python_version>'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.py
    
    - name: Start Server
      run: |
        python main.py & # Starts the server in the background
        
    - name: Check Server
      run: |
        while true; do
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3333/openapi.yaml)
          if [ $STATUS -eq 200 ]; then
            echo "Server is up and running!"
            break
          else
            echo "Server not ready yet, waiting..."
            sleep 5
          fi
        done
